---
  - hosts: all
    become: yes
    tasks:

      - name: update and upgrade apt package
        apt: 
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 

      - name: create the 'student' user
        user: name=student state=present create_home=yes shell=/bin/bash group=student
      
      - name: allow 'student' to have passwordless sudo
        lineinfile:
          dest: /etc/sudoers
          line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
          validate: 'visudo -cf %s'

      - name: set up authorized keys for the student user
        authorized_key: user=student key="{{item}}"
        with_file:
          - ~/.ssh/id_rsa.pub

      - name: install Docker
        apt:
          name: "docker.io"
          state: present
          update_cache: yes
       

      - name: install APT Transport HTTPS
        apt:
          name: apt-transport-https
          state: present

      - name: add Kubernetes apt-key
        apt_key:
          url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          state: present

      - name: add Kubernetes' APT repository
        apt_repository:
          repo: deb http://apt.kubernetes.io/  kubernetes-xenial main
          state: present
          filename: 'kubernetes'

      - name: install kubelet
        apt:
          name: kubelet=1.20.1-00
          state: present
          update_cache: yes

      - name: install kubeadm
        apt:
          name: kubeadm=1.20.1-00
          state: present

      - name: hold the software at the recent but stable version 
        shell: apt-mark hold kubelet kubeadm
        

  - hosts: master
    become: yes
    tasks:

      - name: install kubectl
        apt:
          name: kubectl=1.20.1-00
          state: present
          force: yes

      - name: hold the software at the recent but stable version 
        shell: apt-mark hold kubectl

      - name: Download Calico as a network plugin which will allow us to use Network Policies
        get_url:
          url: https://docs.projectcalico.org/manifests/calico.yaml
          dest: $HOME      


      - name: Set the hostname to k8scp
        hostname:
          name: 'k8scp'

      - name: Delete previous configuration file if present.
        file:
          path:  $HOME/kubeadm-config.yaml
          state: absent

      - name: Create a configuration file for the cluster.
        file:
          path:  $HOME/kubeadm-config.yaml
          state: touch
          owner: root
          group: root
          mode: '0700'
       
      - name: Set the configuration file for the cluster.
        blockinfile:
          path:  $HOME/kubeadm-config.yaml
          marker: ""
          block: |
            apiVersion: kubeadm.k8s.io/v1beta2
            kind: ClusterConfiguration
            kubernetesVersion: 1.20.1
            controlPlaneEndpoint: "k8scp:6443"
            networking:
              podSubnet: 192.168.0.0/16
          
      - name: Initialize the cluster
        shell: 
        args:
          cmd: kubeadm init --config=kubeadm-config.yaml --upload-certs 
          chdir: $HOME

      - name: create .kube directory
        become: yes
        become_user: student
        file:
          path: $HOME/.kube
          state: directory
          mode: '0700'

      - name: copy admin.conf to user's kube config
        become: yes
        become_user: student
        copy:
          src: /etc/kubernetes/admin.conf
          dest: /home/student/.kube/config
          remote_src: yes
          owner: student
          group: student
          mode: '0740'


      - name: Remember to copy the network file to the current, non-root user directory first
        become: yes
        become_user: student
        copy:
          src:  /root/calico.yaml
          dest: /home/student/
          remote_src: yes
          owner: student
          group: student
          mode: '0740'

      - name: install Pod network
        become: yes
        become_user: student
        shell: kubectl apply -f calico.yaml
        args:
          chdir: $HOME
       


  - hosts: master
    become: yes
    become_user: student
    gather_facts: false
    tasks:
      - name: get join command
        shell: kubeadm token create --print-join-command
        register: join_command_raw

      - name: get hostname
        shell: hostname -i
        register: hostname_raw

      - name: set join command
        set_fact:
          join_command: "{{ join_command_raw.stdout_lines[0] }}"

  - hosts: workers
    become: yes
    tasks:


      - name: Ensure we add a local DNS alias for the cp server
        lineinfile:
          dest: /etc/hosts
          regexp: '^127\.0\.1\.1 localhost'
          insertbefore: '^127\.0\.1\.1 localhost'
          line: "{{ hostname_raw.stdout_lines[0]  k8scp }}"
          owner: root
          group: root
          mode: '0700'

      - name: join cluster
        shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
        args:
          chdir: $HOME
          creates: node_joined.txt

